2018-09-18 19:09:26,941 - root - ERROR - Exception (psycopg2.ProgrammingError) can't adapt type 'builtin_function_or_method' [SQL: 'UPDATE "order" SET customer_name=%(customer_name)s WHERE "order".id = %(id_1)s'] [parameters: {'customer_name': 'Ankit Gupta', 'id_1': <built-in function id>}] (Background on this error at: http://sqlalche.me/e/f405) occurred while updating <built-in function id>
2018-09-18 19:09:47,847 - root - ERROR - Exception (psycopg2.ProgrammingError) can't adapt type 'builtin_function_or_method' [SQL: 'UPDATE "order" SET customer_name=%(customer_name)s WHERE "order".id = %(id_1)s'] [parameters: {'customer_name': 'Ankit Gupta', 'id_1': <built-in function id>}] (Background on this error at: http://sqlalche.me/e/f405) occurred while updating <built-in function id>
2018-09-18 19:11:00,423 - root - ERROR - Exception (psycopg2.ProgrammingError) can't adapt type 'builtin_function_or_method' [SQL: 'UPDATE "order" SET customer_name=%(customer_name)s WHERE "order".id = %(id_1)s'] [parameters: {'customer_name': 'Ankit Gupta', 'id_1': <built-in function id>}] (Background on this error at: http://sqlalche.me/e/f405) occurred while updating <built-in function id>
2018-09-18 19:11:28,483 - root - ERROR - Exception (psycopg2.ProgrammingError) can't adapt type 'builtin_function_or_method' [SQL: 'UPDATE "order" SET customer_name=%(customer_name)s WHERE "order".id = %(id_1)s'] [parameters: {'customer_name': 'Ankit Gupta', 'id_1': <built-in function id>}] (Background on this error at: http://sqlalche.me/e/f405) occurred while updating <built-in function id>
2018-09-18 19:32:18,996 - root - ERROR - Integrity Exception (psycopg2.IntegrityError) insert or update on table "storage" violates foreign key constraint "storage_sku_id_fkey"
DETAIL:  Key (sku_id)=(abc) is not present in table "sku_details".
 [SQL: 'INSERT INTO storage (id, stock, sku_id, modified_date) VALUES (%(id)s, %(stock)s, %(sku_id)s, %(modified_date)s)'] [parameters: {'stock': 5, 'sku_id': 'abc', 'id': '3fb33fe8-3e95-465b-875b-c7f3f1ebd4d9', 'modified_date': datetime.datetime(2018, 9, 18, 14, 2, 18, 994872)}] (Background on this error at: http://sqlalche.me/e/gkpj) occurred while inserting {'stock': 5, 'sku_id': 'abc', 'id': '3fb33fe8-3e95-465b-875b-c7f3f1ebd4d9'}
